export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST';
export const STOCK_DETAILS_SUCCESS = 'STOCK_DETAILS_SUCCESS';
export const STOCK_DETAILS_FAILURE = 'STOCK_DETAILS_FAILURE';
export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE';